Fixed: typename before iterator because dependent scope.
G++14:

invokable.hpp:100:13: error: need ‘typename’ before ‘std::vector<callback<A ...> >::iterator’ because ‘std::vector<callback<A ...> >’ is a dependent scope
             std::vector<callback<A...>>::iterator it;